export const CATEGORY_RULES: Record<string, string[]> = {
  // ── Non-rewardable: bank-generated charges ─────────────────────────────
  bank_charges_and_taxes: [
    "AMB CHRG",
    "PENAL CHRG",
    "MIN BAL CHRG",
    "NON-HDFC ATM",
    "NON-HOME BRANCH",
    "CONV FEE",
    "ANNUAL FEE",
    "CHQ RTN",
    "CHEQUE RETURN",
    "STAMP DUTY",
    "IT DEPT",
    "INCOME TAX",
    "GST CHRG",
    "SERVICE CHG",
    "PROCESSING FEE",
    "LATE PAYMENT",
  ],

  // ── Non-rewardable: gambling (excluded from reward calculation) ─────────
  gambling_and_restricted: [
    "MATKA",
    "SATTA",
    "LOTTERY",
    "BETWAY",
    "DREAM11",
    "DREAM 11",
    "RUMMY CIRCLE",
    "RUMMY",
    "POKER",
    "CASINO",
    "BETTING",
  ],

  // ── Non-rewardable: investments & insurance (not card-rewardable) ───────
  investment_and_insurance: [
    "ZERODHA",
    "GROWW",
    "KITE",
    "UPSTOX",
    "INDMONEY",
    "LIC",
    "HDFC LIFE",
    "ICICI PRU",
    "ICICI PRUDENTIAL",
    "POLICYBAZAAR",
    "KUVERA",
    "SMALLCASE",
    "NEXTBI",
    "ANGELONE",
    "ANGELMF",
    "ICCLMF",
    "IPO.",
    "MUTUAL FUND",
    "NAVI MF",
    "MIRAE",
    "NIPPON MF",
    "AXIS MF",
    "SBI MF",
    "PARAG PARIKH",
    "INB MF",
    "CHIT FUND",
    "SAVING SCHEME",
    " SCHEME ", // chit fund schemes (space-delimited)
    "SCHEME-PAYTM", // chit fund / cooperative schemes paid via Paytm
    "NIDHI SCHEME",
  ],

  // ── Non-rewardable: rent & credit card bill payments ───────────────────
  rent_and_credit_card: [
    "CRED",
    "CRED.CLUB",
    "HOUSE RENT",
    "RENTPAY",
    "DREAMPLUG",
    "NOBROKER",
    "MAGICBRICKS RENT",
  ],

  // ── Non-rewardable: loan EMIs ──────────────────────────────────────────
  loans_and_emi: [
    "PERSONAL LOAN",
    " EMI ",
    "EMI-",
    "LOAN CHRG",
    "LOAN EMI",
    "FINSERV",
    "BAJAJ",
    "BAJAJFINSERV",
    "HOME LOAN",
    "CAR LOAN",
    "HDFC LOAN",
    "ICICI LOAN",
    "PIRAMAL",
    "FULLERTON",
    "TATA CAPITAL",
  ],

  // ── Rewardable: digital subscriptions ─────────────────────────────────
  subscriptions_and_digital: [
    "NETFLIX",
    "APPLE MEDIA",
    "APPLE.COM",
    "GOOGLE",
    "SPOTIFY",
    "ADOBE",
    "YOUTUBE",
    "YOUTUBE PREMIUM",
    "DISNEY",
    "HOTSTAR",
    "AMAZON PRIME",
    "SONY LIV",
    "SONYLIV",
    "CANVA",
    "OPENAI",
    "CHATGPT",
    "LINKEDIN",
    "MICROSOFT",
    "DROPBOX",
    "ICLOUD",
  ],

  // ── Rewardable: food & dining ──────────────────────────────────────────
  food_and_dining: [
    "ZOMATO",
    "SWIGGY",
    "MOMOS",
    "NESCAFE",
    "GORDHANDASS",
    "STARBUCKS",
    "DOMINOS",
    "DOMINO",
    "PIZZA HUT",
    "KFC",
    "BURGER KING",
    "MCDONALDS",
    "MCDONALD",
    "CHAIOS",
    "BLUE TOKAI",
    "EATSURE",
    "BLINKIT",
    "ZEPTO",
    "MUJ.4276",
    "BAOZI",
    "DINEOUT",
    "EAZYDINER",
    "FASOOS",
    "BOX8",
    "FRESHMENU",
    "DUNZO",
    "CHAI POINT",
    "CAFE COFFEE",
    "HALDIRAMS",
    "BARBEQUE",
    "MAINLAND CHINA",
  ],

  // ── Rewardable: online shopping & ecommerce ────────────────────────────
  shopping_and_ecommerce: [
    "AMAZON",
    "FLIPKART",
    "MYNTRA",
    "AJIO",
    "NYKAA",
    "MEESHO",
    "RELIANCE DIGITAL",
    "CROMA",
    "TATA CLIQ",
    "ZARA",
    "H&M",
    "DECATHLON",
    "PEPPERFRY",
    "URBAN LADDER",
    "BOAT ",
    "NOISE ",
    "VIJAY SALES",
    "CHROMA",
    "SHREE SHYAM ART",
    "ART AND",
    "MERCHANT",
  ],

  // ── Rewardable: grocery & daily essentials ─────────────────────────────
  grocery_and_essentials: [
    "BIGBASKET",
    "BBDAILY",
    "DMART",
    "D MART",
    "RELIANCE FRESH",
    "RELIANCE SMART",
    "SPENCERS",
    "NATURES BASKET",
    "MILK BASKET",
    "COUNTRY DELIGHT",
    "JIOMART",
    "SMART BAZAAR",
    "MORE SUPERMARKET",
    "STAR BAZAAR",
    "HYPERCITY",
  ],

  // ── Rewardable: health & pharmacy ─────────────────────────────────────
  health_and_wellness: [
    "APOLLO",
    "APOLLO PHARMACY",
    "PHARMEASY",
    "1MG",
    "NETMEDS",
    "CULT.FIT",
    "CULT FIT",
    "PRACTO",
    "MAX HEALTH",
    "TATA 1MG",
    "MEDPLUS",
    "WELLNESS FOREVER",
    "FORTIS",
    "MANIPAL HOSPITAL",
    "THYROCARE",
    "LYBRATE",
  ],

  // ── Rewardable: fuel ──────────────────────────────────────────────────
  fuel: [
    "HPCL",
    "BPCL",
    "IOCL",
    "INDIAN OIL",
    "HINDUSTAN PETROLEUM",
    "BHARAT PETROLEUM",
    "HP PETROL",
    "HP PUMP",
    "ESSAR FUEL",
    "SHELL PETROL",
    "SHELL FUEL",
    "PETROL PUMP",
    "FUEL STATION",
    "NAYARA",
    "RELIANCE PETRO",
    "INDIAN OI",
    "SRINATH INDIAN", // catches "MS SRINATH INDIAN OI" (Indian Oil dealer)
  ],

  // ── Rewardable: travel (flights, hotels, cabs, trains) ────────────────
  travel: [
    "IRCTC",
    "RAILWAYS",
    "RAILWAY",
    "INDIGO",
    "AIR INDIA",
    "SPICEJET",
    "AKASA",
    "GOAIR",
    "VISTARA",
    "AIRINDIA",
    "MAKEMYTRIP",
    "MMT",
    "GOIBIBO",
    "CLEARTRIP",
    "YATRA",
    "OYO",
    "TREEBO",
    "FABHOTELS",
    "AIRBNB",
    "UBER",
    "OLA",
    "RAPIDO",
    "REDBUS",
    "RED_BUS",
    "ABHIBUS",
    "KSRTC",
    "MSRTC",
    "GSRTC",
    "MERU",
    "BLUEBIKE",
    "BLUSMART",
    "DRIVEZY",
    "ZOOMCAR",
  ],

  // ── Rewardable: utilities & telecom bills ─────────────────────────────
  utilities: [
    "JIO",
    "JIOFIBER",
    "AIRTEL",
    "AIRTEL PAYMENTS",
    "BSNL",
    "VODAFONE",
    "VI ",
    "IDEA CELLULAR",
    "TATA SKY",
    "TATAPLAY",
    "TATA PLAY",
    "DISH TV",
    "D2H",
    "SUN DIRECT",
    "BESCOM",
    "MSEB",
    "TNERC",
    "TNEB",
    "BSES",
    "WESCO",
    "NPCL",
    "TORRENT POWER",
    "ADANI ELECTRICITY",
    "ELECTRICITY",
    "WATER BOARD",
    "WATER SUPPLY",
    "MUNICIPAL",
    "BROADBAND",
    "FIBER",
    "PARK+",
    "GPAYRECHARGE",
    "RECHARGE",
    "PREPAID",
    "FASTAG",
    "NHAI",
    "PAYTM RECHARGE",
  ],

  // ── Non-rewardable: P2P UPI transfers ─────────────────────────────────
  // MUST BE LAST — after all merchant keyword categories.
  transfers_and_p2p: [
    "@OKICICI",
    "@OKHDFCBANK",
    "@OKAXIS",
    "@YBL-",
    "@IBL-",
    "@SBIN-",
    "@UBIN-",
    "@BARB-",
    "@PUNB-",
    "@CNRB-",
    "@KKBK-",
    "@SBI-", // SBI personal UPI (narration uses @SBI- not @SBIN-)
    "@HDFC-",
    "@ICICI-",
    "@AXIS-",
    "SENT TO",
    "CASH WITHDRAWAL",
    "SELF TRANSFER",
    "NEFT DR-",
    "IMPS-P2A",
    "P2P TRANSFER",
  ],
};

/**
 * Categorizes a bank transaction based on its narration string.
 * Returns one of the keys in CATEGORY_RULES, or "others" for unmatched.
 * "others" is treated as REWARDABLE (general card spend) by the advisor.
 */
export function getCategory(narration: string): string {
  if (!narration) return "others";
  const norm = narration.toUpperCase();
  for (const [category, keywords] of Object.entries(CATEGORY_RULES)) {
    if (keywords.some((kw) => norm.includes(kw))) {
      return category;
    }
  }
  return "others";
}

/**
 * Categories that CANNOT earn credit card rewards.
 */
export const NON_REWARDABLE_CATEGORIES = new Set([
  "bank_charges_and_taxes",
  "gambling_and_restricted",
  "investment_and_insurance",
  "rent_and_credit_card",
  "loans_and_emi",
  "transfers_and_p2p",
]);

export function isRewardable(category: string): boolean {
  return !NON_REWARDABLE_CATEGORIES.has(category);
}
